export const INCREMENT = 'increment';
export const DECREMENT = 'decrement';
export const SWITCH_THREAD = 'SWITCH_THREAD';
export const RECEIVE_ALL = 'RECEIVE_ALL';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';

// ajax peticiones inicio
export const CARGAR_ESTUDIANTE = 'CARGAR_ESTUDIANTE';
export const CARGAR_LECCIONES_ESTUDIANTES = 'CARGAR_LECCIONES_ESTUDIANTES';
export const CARGAR_LECCIONES_NOTAS = 'CARGAR_LECCIONES_NOTAS';

// PERFIL
export const LECCION_MOSTRAR = 'LECCION_MOSTRAR'; // al momento de dar clic y querer ver una leccion

// ajax otros
export const INGRESAR_CODIGO = 'INGRESAR_CODIGO';

// realtime
export const ENTRAR_TOMAR_LECCION = 'ENTRAR_TOMAR_LECCION';
export const ESPERANDO_LECCION = 'ESPERANDO_LECCION';
export const EMPEZO_LECCION = 'EMPEZO_LECCION';
export const TERMINO_LECCION = 'TERMINO_LECCION';
export const BLOQUEADO_LECCION = 'BLOQUEADO_LECCION';

// RESPUESTAS
export const ENVIAR_RESPUESTA = 'ENVIAR_RESPUESTA';
export const OBTENER_RESPUESTAS = 'OBTENER_RESPUESTAS';
export const TERMINO_CONTESTAR = 'TERMINO_CONTESTAR';
