#! /bin/bash

# COPIAR DEPENDENCIAS DE ATT Y WEBSERVICE
# buscar como usar webservice en otro proceso

# git pull --recurse-submodules
# git submodule update --remote --recursive

# ATT
export NODE_ENV=development
echo "Instalando ATT"
cd att
git reset --hard HEAD
git pull origin master
cd client/estudiantes
echo "Instalando ATT ESTUDIANTES"
yarn
yarn build
cd ..
cd profesores
echo "Instalando ATT PROFESORES"
yarn
yarn build
cd ../../..

# WEBSERVICE

# PPL
git reset --hard HEAD
git pull origin master
cd app_client_v2/estudiantes
yarn
yarn build
cd ../..
yarn

# SET .ENV


# HACER COPIA DE LAS DB


# RUN SERVER