export const INCREMENT = 'increment'
export const DECREMENT = 'decrement'
export const CARGAR_ESTUDIANTE = 'CARGAR_ESTUDIANTE'
export const SWITCH_THREAD = 'SWITCH_THREAD'
export const RECEIVE_ALL = 'RECEIVE_ALL'
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE'
