DROP DATABASE IF EXISTS ppl_development;
CREATE DATABASE ppl_development;
USE ppl_development;

CREATE TABLE profesores(
  id INTEGER UNSIGNED AUTO_INCREMENT NOT NULL UNIQUE,
  nombres CHAR(100) NOT NULL,
  apellidos CHAR(100) NOT NULL,
  correo CHAR(100) NOT NULL,
  created_at TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)ENGINE = InnoDB;

CREATE TABLE materias(
  id INTEGER UNSIGNED AUTO_INCREMENT NOT NULL UNIQUE,
  nombre CHAR(20) NOT NULL,
  codigo CHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)ENGINE = InnoDB;

CREATE TABLE semestres(
  id INTEGER UNSIGNED AUTO_INCREMENT NOT NULL UNIQUE,
  anio CHAR(10) NOT NULL,
  termino CHAR(10) NOT NULL,
  created_at TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)ENGINE = InnoDB;

CREATE TABLE capitulos(
  id INTEGER UNSIGNED AUTO_INCREMENT NOT NULL UNIQUE,
  nombre CHAR(150) NOT NULL,
  created_at TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  materia_id INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FOREIGN KEY (materia_id) REFERENCES materias(id)
)ENGINE = InnoDB;

CREATE TABLE paralelos(
  id INTEGER UNSIGNED AUTO_INCREMENT NOT NULL UNIQUE,
  nombre CHAR(10) NOT NULL,
  created_at TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  materia_id INTEGER UNSIGNED NOT NULL,
  semetre_id INTEGER UNSIGNED  NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FOREIGN KEY (materia_id) REFERENCES materias(id),
  CONSTRAINT FOREIGN KEY (semetre_id) REFERENCES semestres(id)
)ENGINE = InnoDB;

CREATE TABLE lecciones(
  id INTEGER UNSIGNED AUTO_INCREMENT NOT NULL UNIQUE,
  nombre CHAR(200) NOT NULL,
  estado CHAR(20) NOT NULL,
  tiempo_estimado SMALLINT UNSIGNED NOT NULL,
  puntaje FLOAT UNSIGNED NOT NULL,
  tipo CHAR(50) NOT NULL,
  codigo CHAR(50) NOT NULL,
  fecha_estimado TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP,
  fecha_terminado TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  fecha_empezado TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  profesor_id INTEGER UNSIGNED NOT NULL,
  paralelo_id INTEGER UNSIGNED  NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FOREIGN KEY (profesor_id) REFERENCES profesores(id),
  CONSTRAINT FOREIGN KEY (paralelo_id) REFERENCES paralelos(id)
)ENGINE = InnoDB;

CREATE TABLE grupos(
  id INTEGER UNSIGNED AUTO_INCREMENT NOT NULL UNIQUE,
  nombre CHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  paralelo_id INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FOREIGN KEY (paralelo_id) REFERENCES paralelos(id)
)ENGINE = InnoDB;

CREATE TABLE estudiantes(
  id INTEGER UNSIGNED AUTO_INCREMENT NOT NULL UNIQUE,
  nombres CHAR(100) NOT NULL,
  apellidos CHAR(100) NOT NULL,
  correo CHAR(100) NOT NULL,
  matricula CHAR(20) NOT NULL,
  foto_url CHAR(200),
  created_at TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  paralelo_id INTEGER UNSIGNED NOT NULL,
  grupo_id INTEGER UNSIGNED,
  PRIMARY KEY (id),
  CONSTRAINT FOREIGN KEY (paralelo_id) REFERENCES paralelos(id),
  CONSTRAINT FOREIGN KEY (grupo_id) REFERENCES grupos(id)
)ENGINE = InnoDB;

CREATE TABLE preguntas(
  id INTEGER UNSIGNED AUTO_INCREMENT NOT NULL UNIQUE,
  nombre CHAR(100) NOT NULL,
  tipo_leccion CHAR(100) NOT NULL, --  para que sirve?
  tipo_pregunta CHAR(100) NOT NULL,
  tiempo_estimado SMALLINT UNSIGNED NOT NULL,
  descripcion TEXT NOT NULL, --  JSON formato?
  puntaje SMALLINT NOT NULL,
  created_at TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  profesor_id INTEGER UNSIGNED NOT NULL,
  capitulo_id INTEGER UNSIGNED NOT NULL,
  pregunta_raiz INTEGER UNSIGNED,
  PRIMARY KEY (id),
  CONSTRAINT FOREIGN KEY (profesor_id) REFERENCES profesores(id),
  CONSTRAINT FOREIGN KEY (capitulo_id) REFERENCES capitulos(id),
  CONSTRAINT FOREIGN KEY (pregunta_raiz) REFERENCES preguntas(id)
)ENGINE = InnoDB;

CREATE TABLE profesor_paralelos(
  id INTEGER UNSIGNED AUTO_INCREMENT NOT NULL UNIQUE,
  grado_responsabilidad INT,
  created_at TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  paralelo_id INTEGER UNSIGNED NOT NULL,
  profesor_id INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FOREIGN KEY (paralelo_id) REFERENCES paralelos(id),
  CONSTRAINT FOREIGN KEY (profesor_id) REFERENCES profesores(id)
)ENGINE = InnoDB;

CREATE TABLE estudiante_lecciones(
  id INTEGER UNSIGNED AUTO_INCREMENT NOT NULL UNIQUE,
  calificacion FLOAT,
  created_at TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  estudiante_id INTEGER UNSIGNED NOT NULL,
  leccion_id INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FOREIGN KEY (estudiante_id) REFERENCES estudiantes(id),
  CONSTRAINT FOREIGN KEY (leccion_id) REFERENCES lecciones(id)
)ENGINE = InnoDB;

CREATE TABLE preguntas_lecciones(
  id INTEGER UNSIGNED AUTO_INCREMENT NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  pregunta_id INTEGER UNSIGNED NOT NULL,
  leccion_id INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FOREIGN KEY (pregunta_id) REFERENCES preguntas(id),
  CONSTRAINT FOREIGN KEY (leccion_id) REFERENCES lecciones(id)
)ENGINE = InnoDB;

CREATE TABLE respuestas(
  id INTEGER UNSIGNED AUTO_INCREMENT NOT NULL UNIQUE,
  calificacion FLOAT,
  respuesta TEXT NOT NULL,
  feedback TEXT NOT NULL,
  imagen_url CHAR(200) NOT NULL,
  created_at TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  estudiante_id INTEGER UNSIGNED NOT NULL,
  pregunta_leccion_id INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FOREIGN KEY (estudiante_id) REFERENCES estudiantes(id),
  CONSTRAINT FOREIGN KEY (pregunta_leccion_id) REFERENCES preguntas_lecciones(id)
)ENGINE = InnoDB;
